# Generated by Django 5.0.2 on 2024-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modme_id', models.BigIntegerField(unique=True)),
                ('password', models.BigIntegerField(default=1234)),
                ('name', models.CharField(max_length=32)),
                ('coins', models.IntegerField()),
                ('student_group', models.IntegerField(null=True)),
            ],
        ),
    ]
